package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/benfourie/fl/internal/config"
	"github.com/spf13/cobra"
)

var initForce bool

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize fl for the current git repository",
	Long: `Creates a .fl.yaml file at the root of the current git repository.

This file lets you configure fl on a per-repo basis — for example,
using Trello in one repo and Jira in another. It is safe to commit.`,
	Args: cobra.NoArgs,
	RunE: runInit,
}

func init() {
	initCmd.Flags().BoolVarP(&initForce, "force", "f", false, "Overwrite an existing .fl.yaml")
}

func runInit(cmd *cobra.Command, args []string) error {
	root, err := config.GitRoot()
	if err != nil {
		return fmt.Errorf("not inside a git repository")
	}

	cfgPath := filepath.Join(root, ".fl.yaml")
	if _, err := os.Stat(cfgPath); err == nil && !initForce {
		return fmt.Errorf(".fl.yaml already exists at %s (use --force to overwrite)", cfgPath)
	}

	r := bufio.NewReader(os.Stdin)

	// Tracker provider
	fmt.Print("Tracker provider [jira/trello] (default: jira): ")
	provider := readLine(r)
	if provider == "" {
		provider = "jira"
	}
	if provider != "jira" && provider != "trello" {
		return fmt.Errorf("unsupported provider %q — choose jira or trello", provider)
	}

	// Provider-specific config
	var projectsOrBoards string
	switch provider {
	case "jira":
		fmt.Print("Jira project keys to filter by (comma-separated, leave blank for all): ")
		projectsOrBoards = readLine(r)
	case "trello":
		fmt.Print("Trello board IDs to filter by (comma-separated, leave blank for all): ")
		projectsOrBoards = readLine(r)
	}

	// Branch template
	defaultTemplate := "{{.Type}}/{{.Key}}-{{.Title}}"
	fmt.Printf("Branch name template (default: %s): ", defaultTemplate)
	branchTemplate := readLine(r)
	if branchTemplate == "" {
		branchTemplate = defaultTemplate
	}

	content := buildRepoConfig(provider, projectsOrBoards, branchTemplate)

	if err := os.WriteFile(cfgPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing .fl.yaml: %w", err)
	}

	fmt.Printf("Created %s\n", cfgPath)
	fmt.Println("Tip: commit this file so your team shares the same setup.")
	return nil
}

func buildRepoConfig(provider, projectsOrBoards, branchTemplate string) string {
	var sb strings.Builder

	sb.WriteString("# .fl.yaml — repo-level fl configuration\n")
	sb.WriteString("# Generated by `fl init`. Safe to commit.\n\n")

	sb.WriteString("tracker:\n")
	sb.WriteString(fmt.Sprintf("  provider: %s\n", provider))

	switch provider {
	case "jira":
		if projectsOrBoards != "" {
			sb.WriteString("\njira:\n")
			sb.WriteString("  projects:\n")
			for _, p := range splitAndTrim(projectsOrBoards) {
				sb.WriteString(fmt.Sprintf("    - %s\n", p))
			}
		}
	case "trello":
		if projectsOrBoards != "" {
			sb.WriteString("  trello:\n")
			sb.WriteString("    board_ids:\n")
			for _, id := range splitAndTrim(projectsOrBoards) {
				sb.WriteString(fmt.Sprintf("      - %s\n", id))
			}
		}
	}

	sb.WriteString("\nbranch:\n")
	sb.WriteString(fmt.Sprintf("  template: \"%s\"\n", branchTemplate))

	return sb.String()
}

func readLine(r *bufio.Reader) string {
	line, _ := r.ReadString('\n')
	return strings.TrimSpace(line)
}

func splitAndTrim(s string) []string {
	parts := strings.Split(s, ",")
	result := make([]string, 0, len(parts))
	for _, p := range parts {
		if v := strings.TrimSpace(p); v != "" {
			result = append(result, v)
		}
	}
	return result
}
